#!/bin/bash
#
##############################################################
#                                                            #
#                    WPSD MOTD Generator                     #
#                                                            #
##############################################################
#
# Make sure we are root
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Function to check if any network interface has an IP address
interface_has_ip() {
  local interfaces=($(ip -o addr show | awk '{print $2}'))

  for interface in "${interfaces[@]}"; do
    if [[ $interface != "lo" ]]; then
      if ip addr show dev $interface | grep -q 'inet '; then
        return 0
      fi
    fi
  done

  return 1
}
# Wait for an IP address
while ! interface_has_ip; do
    sleep 1
done

source /usr/local/sbin/.wpsd-shell-funcs

# WPSD git id
gitId=$( cat /etc/.W0CHP-PiStar-Dash.remote_version )

echo -e "${COL_REG_CYAN}
██╗    ██╗██████╗ ███████╗██████╗ 
██║    ██║██╔══██╗██╔════╝██╔══██╗
██║ █╗ ██║██████╔╝███████╗██║  ██║
██║███╗██║██╔═══╝ ╚════██║██║  ██║
╚███╔███╔╝██║     ███████║██████╔╝
 ╚══╝╚══╝ ╚═╝     ╚══════╝╚═════╝${COL_NC}
${COL_BRIGHT_CYAN}
(${COL_LIGHT_CYAN}WPSD${COL_NC} Ver.# ${COL_LIGHT_ORANGE}${gitId}${COL_NC})

${INFO} Your WPSD dashboard can be accesed from:
    ${BULL} ${COL_LIGHT_MAGENTA}http://$(hostname)/${COL_NC}
    ${BULL} ${COL_LIGHT_MAGENTA}http://$(hostname).local/${COL_NC}
    ${BULL} ${COL_LIGHT_MAGENTA}http://$(hostname -I | awk '{print $1}')/${COL_NC}

${INFO} WPSD command-line tools are all prefixed with \"wpsd-\".
" > /etc/motd
