#!/bin/bash
#
##############################################################
#                                                            #
#                    WPSD MOTD Generator                     #
#                                                            #
##############################################################
#
# Make sure we are root
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

source /usr/local/sbin/.wpsd-shell-funcs

# WPSD git id
gitId=$( cat /etc/.W0CHP-PiStar-Dash.remote_version )

echo -e "${COL_REG_CYAN}
██╗    ██╗██████╗ ███████╗██████╗ 
██║    ██║██╔══██╗██╔════╝██╔══██╗
██║ █╗ ██║██████╔╝███████╗██║  ██║
██║███╗██║██╔═══╝ ╚════██║██║  ██║
╚███╔███╔╝██║     ███████║██████╔╝
 ╚══╝╚══╝ ╚═╝     ╚══════╝╚═════╝${COL_NC}
${COL_BRIGHT_CYAN}
WPSD${COL_NC} Ver.# ${COL_LIGHT_ORANGE}${gitId}${COL_NC}

${INFO} Your WPSD dashboard can be accesed from:
    ${BULL} ${COL_REG_MAGENTA}http://$(hostname)/${COL_NC}
    ${BULL} ${COL_REG_MAGENTA}http://$(hostname).local/${COL_NC}
    ${BULL} ${COL_REG_MAGENTA}http://$(hostname -I | awk '{print $1}')/${COL_NC}

${INFO} WPSD command-line tools are all prefixed with \"wpsd-\".
" > /etc/motd
