#!/bin/bash
clear
echo -e "\nThe old command 'pistar-mmdvmhshatflash' is deprecated. Please use 'wpsd-modemflash' instead."

echo -e "\nI'll run the command for you in 5 seconds, without any options, so you can see the new help syntax...\n"

sleep 5

exec /usr/local/sbin/wpsd-modemflash
