#!/bin/bash

source /usr/local/sbin/.wpsd-shell-funcs

script_name=$(basename "$0")

clear
echo -e "\n${NOTE} ${COL_LIGHT_YELLOW}Note:${COL_NC} The old command '$script_name' is deprecated. Please use 'wpsd-modem-flash_custom' instead."

echo -e "\nI'll run the command for you in 10 seconds, without any options, so you can read the new help syntax...\n"

for ((i=10; i>=1; i--)); do
  printf "\r${INFO} Starting in $i seconds... Press 'q' to abort "
  if [[ -t 0 ]]; then
    read -t 1 -n 1 key
    if [[ $key == "q" || $key == "Q" ]]; then
      printf "\nAborted by user\n"
      exit 1
    fi
  fi
done

exec /usr/local/sbin/wpsd-modem-flash_custom
