#!/bin/bash
#
##############################################################################
#                                                                            #
#                         Pi-Star MOTD Generator.                            #
#                                                                            #
#     Version 0.9, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#                   Make it simple to update the /etc/motd.                  #
#                                                                            #
##############################################################################
#
# Make sure we are root, if we cant stop the services, the results are a bit hit and miss.
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

COL_NC='\e[0m' # No Color
BOLD='\e[1m'
REVERSE='\e[7m'
COL_LIGHT_GREEN='\e[1;32m'
COL_BRIGHT_GREEN='\e[1;92m'
COL_LIGHT_RED='\e[31m'
COL_BRIGHT_RED='\e[1;31m'
COL_LIGHT_CYAN='\e[1;36m'
COL_REG_CYAN='\e[38;5;30m'
COL_REG_ORANGE='\e[38;5;173m'
COL_LIGHT_BLUE='\e[1;46m'
COL_LIGHT_MAGENTA='\e[1;35m'
COL_LIGHT_YELLOW='\e[1;93m'
COL_REG_YELLOW='\e[93m'
INFO="${BOLD}[i]${COL_NC}"
TICK="${BOLD}[${COL_LIGHT_GREEN}✓${COL_NC}]"
CROSS="${BOLD}[${COL_BRIGHT_RED}✗${COL_NC}]"
DONE="${BOLD}${COL_LIGHT_GREEN}Done!${COL_NC}"

# WPSD git id
gitId=$( cat /etc/.W0CHP-PiStar-Dash.remote_version )

echo -e "
${COL_LIGHT_CYAN}' ##:::::'##:'########:::'######::'########:::
  ##:'##: ##: ##.... ##:'##... ##: ##.... ##::
  ##: ##: ##: ##:::: ##: ##:::..:: ##:::: ##::
  ##: ##: ##: ########::. ######:: ##:::: ##::
  ##: ##: ##: ##.....::::..... ##: ##:::: ##::
  ##: ##: ##: ##::::::::'##::: ##: ##:::: ##::
 . ###. ###:: ##::::::::. ######:: ########:::
 :...::...:::..::::::::::......:::........::::${COL_NC}
${COL_LIGHT_CYAN}
W0CHP-PiStar-Dash${COL_NC} Ver.# ${COL_REG_YELLOW}${gitId}${COL_NC}

${INFO} Your dashboard can be accesed from:
${COL_LIGHT_MAGENTA}http://$(hostname)/  http://$(hostname).local/   http://$(hostname -I | awk '{print $1}')/${COL_NC}

${INFO} Pi-star command-line tools all begin with \"pistar-\".
" > /etc/motd
