#!/bin/bash
#
###############################################################################
#                                                                             #
#                           WPSD Update Program                               #
#                                 by W0CHP                                    #
#                                                                             #
###############################################################################
#

if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

exec 200>/var/lock/wpsd-update.lock || exit 1
if ! flock -n 200 ; then
  echo -e "Another instance is already running...\n"
  exit 1
fi

script_name=$(basename "$0")

source /usr/local/sbin/.wpsd-common-funcs

# legacy config migration
legacy_config_php="/var/www/dashboard/config/config.php"
legacy_language_php="/var/www/dashboard/config/language.php"
legacy_ircddblocal_php="/var/www/dashboard/config/ircddblocal.php"
new_config="/etc/WPSD-Dashboard-Config.ini"
if [[ ! -f "$new_config" || ! -s "$new_config" ]]; then
    echo "[WPSD]" > "$new_config"
    echo "Callsign = " >> "$new_config"
    echo "Timezone = " >> "$new_config"
    echo "DashLanguage = " >> "$new_config"
    echo "TimeFormat = " >> "$new_config"
    echo "UpdateNotifier = " >> "$new_config"
fi
time_format=$(grep -oP "define\('TIME_FORMAT', '\K[0-9]+" "$legacy_config_php")
auto_update_check=$(grep -oP "define\('AUTO_UPDATE_CHECK', '\K\w+" "$legacy_config_php")
timezone=$(grep -oP "date_default_timezone_set\('\K[^']+" "$legacy_config_php")
pistar_language=$(grep -oP "pistarLanguage='\K[^']+" "$legacy_language_php")
callsign=$(grep -oP "callsign='\K[^']+" "$legacy_ircddblocal_php")
if [[ -z "$callsign" ]]; then
    :
else
    # Update the new config file with the extracted values
    if [[ -n "$callsign" ]]; then
        sed -i "s|^Callsign = .*|Callsign = $callsign|" "$new_config"
    fi
    if [[ -n "$time_format" ]]; then
        sed -i "s|^TimeFormat = .*|TimeFormat = $time_format|" "$new_config"
    fi
    if [[ -n "$auto_update_check" ]]; then
        sed -i "s|^UpdateNotifier = .*|UpdateNotifier = $auto_update_check|" "$new_config"
    fi
    if [[ -n "$timezone" ]]; then
        sed -i "s|^Timezone = .*|Timezone = $timezone|" "$new_config"
    fi
    if [[ -n "$pistar_language" ]]; then
        sed -i "s|^DashLanguage = .*|DashLanguage = $pistar_language|" "$new_config"
    fi
fi

# connectivity check
conn_check() {
    echo -e "\n${BULL} Checking connectivity to the WPSD Update System..."
    status_code=$(curl -m 30 -A "ConnCheck WPSD-Update (Manual-Update) ${uaStr}" --write-out %{http_code} --silent --output /dev/null "${CONN_CHECK_URI}")
    sleep 1
    if [[ $status_code == 20* ]] || [[ $status_code == 30* ]] ; then
	echo -e "  ${COL_BRIGHT_GREEN}${TICK} Connection established!\n"
    else
	echo -e "  ${CROSS} ${COL_BRIGHT_RED}ERROR:${COL_NC} Cannot connect to the WPSD Update System. Try again later. Exiting...\n"
	exit 1
    fi
}

git_checkUpdateRequired() {
    # Set the function variables
    gitFolder=${1}
    gitRemoteURL=$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git config --get remote.origin.url)
    # WPSD has more than one branch. So depending on what W0CHP branch the user has installed, check that branch.
    gitBranch="$( git --git-dir=${gitFolder}/.git symbolic-ref --short HEAD )"

    # Git check / update function
    gitStatusRemote=$(env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-UpdateCheck (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git ls-remote --heads ${gitRemoteURL} | grep ${gitBranch} | awk {'print $1'})
    gitStatusLocal=$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git log ${gitBranch} --pretty=tformat:"%H" -1)

    # Return the output
    if [[ ${gitStatusRemote} != ${gitStatusLocal} ]]; then
	echo "1"
    else
	echo "0"
    fi
}

git_update() {
    # Set the function variables
    gitFolder=${1}
    # get proper WPSD dash branch user is running...
    dash_branch="$( git --git-dir=${gitFolder}/.git symbolic-ref --short HEAD )"

    # # get rid of legacy index not that upnp rules are in /etc/wpsd-upnp-rules
    if [[ ${gitFolder} == "/usr/local/sbin" ]]; then
	git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git update-index --no-assume-unchanged pistar-upnp.service > /dev/null 2>&1
    fi

    if [[ $(git_checkUpdateRequired ${gitFolder}) -gt 0 ]]; then
        echo -e "  ${COL_LIGHT_MAGENTA}${NOTE} Updates found - Installing now..."
        # WPSD has more than one branch. So depending on what W0CHP branch the user has installed, pull that branch.
        if [[ ${gitFolder} == "/var/www/dashboard" ]]; then
	    cd ${gitFolder}
	    git stash clear > /dev/null 2>&1 # housekeeping
	    git reset --hard origin/master > /dev/null 2>&1
	    env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin ${dash_branch} > /dev/null 2>&1
	    git reset --hard origin/master > /dev/null 2>&1
	    git stash clear > /dev/null 2>&1 # housekeeping
	    echo -e "  ${TICK} Updates installed!"
	else
	    if [[ ${gitFolder} == "/usr/local/sbin" ]]; then
		cd ${gitFolder}
		env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git fetch > /dev/null 2>&1
		if [ "$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git diff --name-only origin/master 2>/dev/null | grep wpsd-update 2>/dev/null)" = "wpsd-update" ]; then
		    # New updater version - Self-update and re-exec:
		    echo -e "\n  ${COL_LIGHT_BLUE}${INFO} New version of the Updater available. Performing self-update..."
		    env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin master > /dev/null 2>&1
		    echo -e "  ${TICK} Updates installed!"
		    if [[ $(git_checkUpdateRequired ${gitFolder}) -gt 0 ]]; then
			echo -e "  ${NOTE} Forcing update..."
			if [ -f ${gitFolder}/pistar-upnp.service ]; then
			    rm -f ${gitFolder}/pistar-upnp.service
			fi
			env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master
			env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin master > /dev/null 2>&1
		    fi
		    echo -e "\n  ${COL_LIGHT_BLUE}${INFO} Relaunching Updater with the new version in 3 seconds..."
		    sleep 4
		    exec "$0" "$@"
		    exit 1
		fi
	    fi
            if [[ ${gitFolder} == "/opt/cast" ]]; then # dvmega cast logic
                env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master > /dev/null 2>&1
                env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin master > /dev/null 2>&1
                env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master > /dev/null 2>&1
	    fi
	    if [[ ${gitFolder} == "/usr/local/bin" ]]; then
		# Update the Binaries
		env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin master > /dev/null 2>&1
		env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master > /dev/null 2>&1
	    fi
	    echo -e "  ${TICK} Updates installed!"
        fi
	# Re-check that the updates are now good
	if [[ $(git_checkUpdateRequired ${gitFolder}) -gt 0 ]]; then
	    if [[ ${gitFolder} == "/usr/local/sbin" ]]; then
		rm -rf ${gitFolder}/pistar-upnp.service
	    fi
	    # Updates were not successful, reverting to original files...
	    # WPSD has more than one branch. So depending on what W0CHP branch the user has installed, pull that branch.
	    if [[ ${gitFolder} == "/var/www/dashboard" ]]; then
		env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/${dash_branch}
	    else
		env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master
	    fi
	fi
    else
	echo -e "  ${INFO} No updates required."
    fi
}

term_banner() {
    clear
    echo -e -n "${COL_LIGHT_CYAN}${BOLD}"
    echo '    _      _____  _______ 
   | | /| / / _ \/ __/ _ \
   | |/ |/ / ___/\ \/ // /
   |__/|__/_/  /___/____/'
    echo -e -n "${COL_NC}${COL_LIGHT_ORANGE}${BOLD}WPSD Software Update Utility${COL_NC}\n"
}

perform_update() {
    pkill .wpsd-slipstream-tasks > /dev/null 2>&1
    pkill .wpsd-running-tasks > /dev/null 2>&1

    if [ -t 1 ] ; then
	if ! [ $(cat /lib/systemd/system/nginx.service | grep -o "mkdir") ]; then
	    sed -i '\/PIDFile=\/run\/nginx.pid/a ExecStartPre=\/bin\/mkdir -p \/var\/log\/nginx' /lib/systemd/system/nginx.service
	    systemctl daemon-reload
	    systemctl restart nginx.service
	    echo -e "  ${NOTE} ${COL_LIGHT_YELLOW}Note:${COL_NC} Web server configuration has been updated by operating system; restarting update..."
	    exec "$0" "$@"
	    exit 1
	fi
    fi

    conn_check
    echo -e "${BULL} Stopping WPSD Services. Please wait..."
    wpsd-services fullstop > /dev/null 2>&1
    process_log_file > /dev/null 2>&1
    echo -e "  ${TICK} Done!\n"

    echo -e "${BULL} Updating WPSD Utilities and Support Programs..."
    git_update /usr/local/sbin
    echo ""

    echo -e "${BULL} Updating WPSD Web Dashboard Software..."
    git_update /var/www/dashboard
    echo ""

    echo -e "${BULL} Updating WPSD Digital Voice-Related Binaries..."
    git_update /usr/local/bin
    echo ""

    # dvmega cast-specific stuff
    castResult=$(isDVmegaCast)
    if [ "$castResult" == "true" ]; then
	echo -e "${BULL} Updating WPSD DVMega CAST Software..."
	# setup local cast repo and link repo to cast PATH
	if [ ! -d '/opt/cast' ] ; then
	   cd /usr/local/sbin
	   git reset --hard > /dev/null 2>&1

	   systemctl stop castudp.service > /dev/null 2>&1
	   systemctl stop castserial.service > /dev/null 2>&1

	   git clone https://wpsd-swd.w0chp.net/WPSD-SWD/DVMega-Cast.git /opt/cast > /dev/null 2>&1
	   cd /opt/cast
	   git checkout master > /dev/null 2>&1
	   git reset --hard origin/master > /dev/null 2>&1

	   rm -rf /usr/local/cast/sbin
	   ln -s /opt/cast/usr-local-cast-sbin /usr/local/cast/sbin > /dev/null 2>&1

	   rm -rf /usr/local/cast/bin
	   ln -s /opt/cast/usr-local-cast-bin /usr/local/cast/bin > /dev/null 2>&1

	   systemctl start castudp.service > /dev/null 2>&1
	   systemctl start castserial.service > /dev/null 2>&1

	   mkdir /usr/local/cast/etc > /dev/null 2>&1
	   cp -a /opt/cast/cast-factory-settings/* /usr/local/cast/etc/ > /dev/null 2>&1
	fi
	if [ -d '/opt/cast' ] ; then
	    # setup the memory-list and firmware upgrade www symlinks if they don't exist yet.
	    if [ ! -L '/var/www/dashboard/admin/cast' ] && [ ! -d '/var/www/dashboard/admin/cast' ]; then
		ln -s /opt/cast/usr-local-cast-www /var/www/dashboard/admin/cast > /dev/null 2>&1
	    fi
	    # setup central fw upload dir.
	    if [ ! -d '/opt/cast/usr-local-cast-www/cast-firmware/fw' ]; then
		mkdir /opt/cast/usr-local-cast-www/cast-firmware/fw
	    fi
	fi
	# ensure configs always have proper perms
	chmod 775 /usr/local/cast/etc
	chown -R www-data:pi-star /usr/local/cast/etc
	chmod 664 /usr/local/cast/etc/*

	# www is a symlink so get main perms setup
	chmod 775 /opt/cast/usr-local-cast-www
	chmod 775 /opt/cast/usr-local-cast-www/cast-firmware/fw
	chown -R www-data:www-data /opt/cast/usr-local-cast-www

	git_update /opt/cast
	echo ""
    fi

    echo -e "${BULL} Updating Hostfiles, User ID DB's & Talkgroup Lists..."
    /usr/local/sbin/wpsd-hostfile-update > /dev/null 2>&1
    echo -e "  ${TICK} Done!\n"

    echo -e "${BULL} Performing maintenance tasks..."

    # check if user already has firewall disabled, and if so, ensure it's kept that way.
    if ! grep -q LOGNDROP /etc/iptables.rules ; then
	/usr/local/sbin/wpsd-system-manager -dfw > /dev/null 2>&1
    else
	/usr/local/sbin/wpsd-system-manager -efw > /dev/null 2>&1
    fi

    /usr/local/sbin/.wpsd-backend-maint > /dev/null 2>&1

    # setup our own native NextionDriver service...
    # Updated 2/23/2023 - W0CHP:
    # TGIFspots contain really weird hacks/scripts, etc.[1] for their Nextion
    # screens, and it all collides with WPSD and our native Nextion driver
    # support.  So lets ignore TGIFspots altogether.
    # [1] <https://github.com/EA7KDO/Scripts>
    if [ -f '/etc/cron.daily/getstripped' ] || [ -d '/usr/local/etc/Nextion_Support/' ] || [ -d '/Nextion' ] ; then # these are hacks that seem to exist on TGIFspots.
	:
    else # yay no tgifspot hacks!
	if [ ! -f '/lib/systemd/system/nextiondriver.service' ] ; then # lets get a native service placeholder installed at the very least
	    curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/mmdvmhost.service-W0CHP  -o /lib/systemd/system/mmdvmhost.service
	    curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/nextiondriver.service-W0CHP  -o /lib/systemd/system/nextiondriver.service
	    # Enable the NextionDriver service
	    systemctl daemon-reload > /dev/null 2>&1
	    systemctl stop nextiondriver.service > /dev/null 2>&1
	    /usr/bin/killall NextionDriver > /dev/null 2>&1
	    systemctl enable nextiondriver.service > /dev/null 2>&1
	fi
	if [ -f '/lib/systemd/system/nextiondriver.service' ] ; then # for non-Nextion instances, ensure existing service is ours vs. ON7LDS'
	    if systemctl status nextiondriver.service | grep masked > /dev/null 2>&1 ; then
		systemctl unmask nextiondriver.service > /dev/null 2>&1
		systemctl daemon-reload > /dev/null 2>&1
	    fi
	    if [ "`sed -nr "/^\[General\]/,/^\[/{ :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/mmdvmhost | grep "Display" | cut -d= -f 2`" != "Nextion" ]; then
		if grep -qo 'killall' /lib/systemd/system/nextiondriver.service ; then
		    curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/mmdvmhost.service-W0CHP  -o /lib/systemd/system/mmdvmhost.service
		    curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/nextiondriver.service-W0CHP  -o /lib/systemd/system/nextiondriver.service
		    systemctl daemon-reload > /dev/null 2>&1
		    systemctl stop nextiondriver.service > /dev/null 2>&1
		    /usr/bin/killall NextionDriver > /dev/null 2>&1
		    systemctl enable nextiondriver.service > /dev/null 2>&1
		fi
	    fi
	fi
	# now, disable nextion driver stuff if display != Nextion in mmdvmhost config...
	if [ "`sed -nr "/^\[General\]/,/^\[/{ :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/mmdvmhost | grep "Display" | cut -d= -f 2`" != "Nextion" ]; then
	    if grep -qo 'Requires=nextiondriver.service' /lib/systemd/system/mmdvmhost.service ; then # if nextion is re'q, get rid of it
		sed -i '/Requires=nextiondriver.service/d' /lib/systemd/system/mmdvmhost.service
		systemctl daemon-reload > /dev/null 2>&1
	    fi
	    if grep -qo 'RequiredBy=mmdvmhost.service' /lib/systemd/system/nextiondriver.service ; then # if mmdvmhost is re'q, get rid of it
		sed -i '/RequiredBy=mmdvmhost.service/d' /lib/systemd/system/nextiondriver.service
		    systemctl daemon-reload > /dev/null 2>&1
	    fi
	    # stop and disable
	    if ! systemctl status nextiondriver.service | grep 'disabled;' > /dev/null 2>&1 ; then
		systemctl stop nextiondriver.service > /dev/null 2>&1
		/usr/bin/killall NextionDriver > /dev/null 2>&1
		systemctl disable nextiondriver.service > /dev/null 2>&1
		systemctl daemon-reload > /dev/null 2>&1
	    fi
	fi
	# user has Nextion defined in mmdvmhost, so let's natively support it:
	if [ "`sed -nr "/^\[General\]/,/^\[/{ :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/mmdvmhost | grep "Display" | cut -d= -f 2`" = "Nextion" ]; then
	    if grep -qo 'killall' /lib/systemd/system/nextiondriver.service ; then # our native support has not been installed/config'd, user likely using ON7LDS script - init!
		systemctl stop nextiondriver.service > /dev/null 2>&1
		/usr/bin/killall NextionDriver > /dev/null 2>&1
		curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/mmdvmhost.service-W0CHP  -o /lib/systemd/system/mmdvmhost.service
		curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/nextiondriver.service-W0CHP  -o /lib/systemd/system/nextiondriver.service
		systemctl daemon-reload > /dev/null 2>&1
		systemctl enable nextiondriver.service > /dev/null 2>&1
		systemctl restart nextiondriver.service > /dev/null 2>&1
		systemctl restart mmdvmhost.service > /dev/null 2>&1
	    fi
	fi
    fi

    # if css does not exist, install default one
    if [ ! -f "/etc/pistar-css.ini" ] ; then
	curl -Ls -A "${uaStrSF}" $SUPPORTING_FILES_REPO/pistar-css-W0CHP.ini -o /etc/pistar-css.ini
    fi

    # Get and cache latest W0CHP-PiStar-Dash version from remote Git repo:
    gitFolder="/var/www/dashboard"
    gitRemoteURL=$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git config --get remote.origin.url)
    gitBranch="$( git --git-dir=${gitFolder}/.git symbolic-ref --short HEAD )"
    gitStatusRemote=$(env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update Version Cacher (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${osName}]" git ls-remote --heads ${gitRemoteURL} ${gitBranch} | grep ${gitBranch} | awk {'print $1'} | awk '{ print substr($1,1,10) }') # last pipe to awk: converts long hash to 10 chars.
    echo ${gitStatusRemote} > /etc/.WPSD_remote_version

    # log file perms
    chown -R mmdvm:mmdvm /var/log/pi-star > /dev/null 2>&1
    chmod 775 /var/log/pi-star > /dev/null 2>&1

    bash /usr/local/sbin/.wpsd-sys-cache >/dev/null 2>&1

    systemctl restart wpsd-running-tasks.service >/dev/null 2>&1

    echo -e "  ${TICK} Done!" # maint. complete

    echo -e "\n${BULL} Starting WPSD Services. Please wait..."
    wpsd-services start > /dev/null 2>&1
    echo -e "  ${TICK} Done!\n"


    if [ -t 1 ]; then
    # This is running from a terminal, so it should be safe to update the OS
	if [ "$1" == "os" ]; then
	    echo -e "${BULL} Checking for any available operating system updates."
	    echo -e "  Please wait..."
	    apt-get -q=2 update
	    if ! apt-get upgrade --dry-run | grep -qw "0 upgraded"; then
		echo -e "  ${COL_LIGHT_MAGENTA}${INFO} Operating system updates available; installing now..."
		apt-get upgrade --fix-missing --fix-broken -y
		apt-get -q=2 autoremove -y
		apt-get -q=2 clean
		apt-get -q=2 autoclean
		echo -e "  ${TICK} Done!\n"
	    else
		echo -e "  ${INFO} No operating system updates required.\n"
	    fi
	else
	    echo -e "${BULL} ${COL_LIGHT_BLUE}${INFO} Operating system is ${BOLD}not${COL_NC} updated by default..."
	    echo -e "      To check for and install OS updates, run this"
	    echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update os${COL_NC}'\n"
	fi
    fi

    /bin/sync
    /bin/sync
    /bin/sync

    if [ -t 1 ]; then # term. vs. web output...
	echo -e "${COL_REG_CYAN}+-------------------------------------------+${COL_NC}"
	echo -e "${COL_REG_CYAN}|                                           |${COL_NC}"
	echo -e "${COL_REG_CYAN}|  ${TICK} ${COMPL} Update Process Finished!   ${COL_REG_CYAN}|${COL_NC}"
	echo -e "${COL_REG_CYAN}|                                           |${COL_NC}"
	echo -e "${COL_REG_CYAN}+-------------------------------------------+${COL_NC}\n"
    else
	echo -e "${TICK} ${COMPL} Update Process Finished!"
	#echo -e "<b>(<a style='color:white;text-decoration:underline;'' href='/config/changelog.php'>Changelog</a>)</b>"
	echo -e "<h3><a style='color:white;text-decoration:underline;'' href='/'>Back to Dashboard <span style='font-size: 30px;'>&larr;</span></a></h3>"
    fi
}

# Do the deeds, y0!
if [ -t 1 ]; then
    # run via terminal, only output to screen
    export FORCE_COLOR=1
    term_banner
    perform_update "$@"
else
    # if not run via terminal, log everything into a log file
     perform_update >> /var/log/pi-star/WPSD-update.log 2>&1
fi

exit 0

