#!/bin/bash
#########################################################
#                                                       #
#              Host, TG, and ID DB files Updater        #
#                       by W0CHP                        #
#                                                       #
#########################################################

# Check if we are root
if [ "$(id -u)" != "0" ];then
    echo "This script must be run as root" 1>&2
    exit 1
fi

source /usr/local/sbin/.wpsd-common-funcs

# check age of task marker file if it exists, and if it's < 8 hours young, bail.
if [[ ${FORCE} -ne 1 ]] ; then # please be thoughtful here. This env. var. is called by a few places in the admin pages.
    if [  -f '/var/run/hostfiles-up' ] && [ "$(( $(date +"%s") - $(stat -c "%Y" "/var/run/hostfiles-up") ))" -lt "28880" ]; then
	echo "Hostfles are less than 8 hours old. Not updating."
	echo "To force an update, run 'sudo env FORCE=1 $(basename "$0")'"
	exit 1
    fi
fi

exec 200>/var/lock/wpsd-hostfiles.lock || exit 1 # only one exec per time
if ! flock -n 200 ; then
  echo "Process already running"
  exit 1
fi

ProgVer="WPSD-HostFileUpdater v.3.2"

# connectivity check
status_code=$(curl -m 6 -A "${ProgVer}  ConnCheck ${uaStr}" --write-out %{http_code} --silent --output /dev/null ${hostFileURL})
if [[ $status_code == 20* ]] || [[ $status_code == 30* ]] ; then
    echo "WPSD Hostfile Update Server connection OK...updating hostfiles."
else
    echo "WPSD Hostfile Update Server connection failed."
    exit 1
fi

if [ ! -d /usr/local/etc/tmp ]; then
    mkdir -p /usr/local/etc/tmp
fi
rm -rf /usr/local/etc/*.2024*
rm -rf /usr/local/etc/*csv*
rm -rf /usr/local/etc/index.*

DExtraHOSTS=/usr/local/etc/tmp/DExtra_Hosts.txt
DMRIDFILE=/usr/local/etc/tmp/DMRIds.dat
DMRHOSTS=/usr/local/etc/tmp/DMR_Hosts.txt
DPlusHOSTS=/usr/local/etc/tmp/DPlus_Hosts.txt
M17HOSTS=/usr/local/etc/tmp/M17Hosts.txt
YSFHOSTS=/usr/local/etc/tmp/YSFHosts.txt
XLXHOSTS=/usr/local/etc/tmp/XLXHosts.txt
BMTGNAMES=/usr/local/etc/tmp/BM_TGs.json
RADIOIDDB_TMP=/usr/local/etc/tmp/user.csv.tmp
RADIOIDDB=/usr/local/etc/tmp/user.csv
GROUPSTXT=/usr/local/etc/tmp/groups.txt
STRIPPED=/usr/local/etc/tmp/stripped.csv

# Generate Host Files
curl --fail -L -o /usr/local/etc/tmp/wpsd-hostfiles.tar.bz2 -s ${hostFileURL}/wpsd-hostfiles.tar.bz2 --user-agent "${ProgVer} ${uaStr}"

tar jxf /usr/local/etc/tmp/wpsd-hostfiles.tar.bz2 -C /usr/local/etc/tmp/

if [ -f /etc/hostfiles.nodextra ]; then
  # Move XRFs to DPlus Protocol
  mv /usr/local/etc/tmp/DPlus_WithXRF_Hosts.txt ${DPlusHOSTS}
  mv /usr/local/etc/tmp/DExtra_NoXRF_Hosts.txt ${DExtraHOSTS}
fi

# Grab DMR IDs
mv ${DMRIDFILE}.bz2 /tmp/
bunzip2 -f /tmp/DMRIds.dat.bz2
# filter out IDs less than 7 digits (causing collisions with TGs of < 7 digits in "Target" column"
cat /tmp/DMRIds.dat  2>/dev/null | grep -v '^#' | awk '($1 > 999999) && ($1 < 10000000) { print $0 }' | sort -un -k1n -o ${DMRIDFILE}
rm -f /tmp/DMRIds.dat

# BM TG List for live caller and (legacy) nextion screens:
cp ${BMTGNAMES} ${GROUPSTXT}

# If there is a DMR override file, add its contents to DMR_Hosts.txt
if [ -f "/root/DMR_Hosts.txt" ]; then
	cat /root/DMR_Hosts.txt >> ${DMRHOSTS}
fi

# Add custom YSF Hosts
if [ -f "/root/YSFHosts.txt" ]; then
	cat /root/YSFHosts.txt >> ${YSFHOSTS}
fi

# Fix DMRGateway issues with parens
if [ -f "/etc/dmrgateway" ]; then
	sed -i '/Name=.*(/d' /etc/dmrgateway
	sed -i '/Name=.*)/d' /etc/dmrgateway
fi

# Add custom P25 Hosts
if [ -f "/root/P25Hosts.txt" ]; then
	cat /root/P25Hosts.txt > /usr/local/etc/P25HostsLocal.txt
fi

# Add local override for M17Hosts
if [ -f "/root/M17Hosts.txt" ]; then
	cat /root/M17Hosts.txt >> ${M17HOSTS}
fi

# Fix up new NXDNGateway Config HostFile setup
if [ ! -f "/root/NXDNHosts.txt" ]; then
	touch /root/NXDNHosts.txt
fi
if [ ! -f "/usr/local/etc/NXDNHostsLocal.txt" ]; then
	touch /usr/local/etc/NXDNHostsLocal.txt
fi

# Add custom NXDN Hosts
if [ -f "/root/NXDNHosts.txt" ]; then
	cat /root/NXDNHosts.txt > /usr/local/etc/NXDNHostsLocal.txt
fi

# XLX override handling
if [ -f "/root/XLXHosts.txt" ]; then
    while IFS= read -r line; do
        if [[ $line != \#* && $line = *";"* ]]; then
            xlxid=$(echo "$line" | awk -F ';' '{print $1}')
            xlxip=$(echo "$line" | awk -F ';' '{print $2}')
            xlxroom=$(echo "$line" | awk -F ';' '{print $3}')
            xlxNewLine="${xlxid};${xlxip};${xlxroom}"
            
            if grep -q "^${xlxid};" ${XLXHOSTS}; then
                sed -i "s/^${xlxid};.*/${xlxNewLine}/" ${XLXHOSTS}
            else
                echo "$xlxNewLine" >> ${XLXHOSTS}
            fi
        fi
    done < "/root/XLXHosts.txt"
    sort -o ${XLXHOSTS} -t ';' -k1,1 ${XLXHOSTS}
fi

# Nextion and LiveCaller DMR ID DB's
bunzip2 -f ${RADIOIDDB}.bz2
mv $RADIOIDDB $RADIOIDDB_TMP
# sort
cat ${RADIOIDDB_TMP} | sort -un -k1n -o ${RADIOIDDB}
rm -f $RADIOIDDB_TMP
# remove header
sed -i '1d' ${RADIOIDDB}

# commit!
rm -rf /usr/local/etc/tmp/*bz2
mv /usr/local/etc/tmp/* /usr/local/etc/
# make link for legacy nextion configs
rm -rf ${STRIPPED}
rm -rf /usr/local/etc/stripped.csv
ln -s /usr/local/etc/user.csv /usr/local/etc/stripped.csv

touch /var/run/hostfiles-up # create/reset marker

if [ -t 1 ] ; then
    echo -e "DONE."
else
    echo -e "* DONE *"
fi

pattern="/usr/local/etc/stripped.csv.*"
files=($pattern)
if [ ${#files[@]} -gt 0 ]; then
  for file in "${files[@]}"; do
     rm -f "$file"
  done
fi

exit 0

